language: php

dist: xenial

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - DB=mysql DB_DSN='mysql://root@127.0.0.1/cake_api_baselayer_test?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'

before_install:
    - mysql -u root -e 'CREATE DATABASE cake_api_baselayer_test;

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer check